package:
  name: fedoo
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/fedoo.git

build:
  number: 0

requirements:
  host:
    - python=3.9
    - setuptools>=58
    - pip=21
    - scipy=1.7.3
    - numpy=1.22.0
    - matplotlib=3.5.1
    - pandas=1.3
    - simcoon=1.0.0
    - pardiso4py
  run:
    - python=3.9
    - numpy=1.22.0
    - scipy=1.7.3
    - pandas=1.3
    - simcoon=1.0.0
    - matplotlib=3.5.1

test:
  imports:
    - fedoo
