package:
  name: fedoo
  version: "0.4.0"

source:
  git_url: https://github.com/3MAH/fedoo.git
  
build:
  noarch: python
  script: pip install .
  
requirements:
  host:
    - python
    - pip
  run:
    - python>=3.10
    - numpy>=1.26
    - scipy
    - pyvista>=0.39
    - simcoon>=1.9.6
    - pypardiso # [x86]

test:
  imports:
    - fedoo
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests
