{% set pyproject = load_file_data("pyproject.toml") %}
{% set version = pyproject["project"]["version"] %}

package:
  name: fedoo
  version: {{ version }}

source:
  git_url: https://github.com/3MAH/fedoo.git
  
build:
  noarch: python
  script: pip install .
  
requirements:
  host:
    - python
    - pip
  run:
    - python>=3.10
    - numpy>=1.26
    - scipy
    - pyvista>=0.42
    - simcoon>=1.9.6
    - {{ solver_backend }}

test:
  imports:
    - fedoo
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests
