package:
  name: fedoo
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/fedoo.git

build:
  noarch: python

requirements:
  host:
    - python=3.9
    - setuptools
    - pip
    - scipy
    - numpy=1.21.4
    - simcoon=1.0.0
  run:
    - python=3.9

test:
  imports:
    - fedoo
