package:
  name: fedoo
  version: 1.0.0

source:
  git_url: https://github.com/3MAH/fedoo.git

build:
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - pip
    - scipy
    - numpy=1.22
    - matplotlib
    - pandas
    - simcoon
    - pardiso4py
  run:
    - python
    - numpy=1.22
    - scipy
    - pandas
    - simcoon
    - matplotlib

test:
  imports:
    - fedoo
