name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5

      - name: Fail if pre-commit failed
        if: steps.pre-commit.outcome == 'failure'
        run: exit 1
